// Builds public/js/icons.js — inline SVGs for every lucide icon the site uses.
// The lucide UMD bundle shipped in node_modules carries NO icon payload
// (createIcons only), so we render the icons ourselves from the ESM source
// trees. Run with: node scripts/generate-icons.js

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ICONS_DIR = path.join(ROOT, 'node_modules/lucide/dist/esm/icons');
const DEFAULT_ATTRS_FILE = path.join(ROOT, 'node_modules/lucide/dist/esm/defaultAttributes.js');
const OUT = path.join(ROOT, 'public/js/icons.js');

const NEEDED_ICONS = [
  'menu',
  'x',
  'arrow-down',
  'arrow-up-right',
  'chevrons-down',
  'lightbulb',
  'rocket',
  'shield-check',
  'globe',
  'coffee',
  'calendar-clock',
  'check',
  'external-link',
  'network',
  'mail',
  'send',
  'circle-check',
  'circle-alert',
  'chevron-left',
  'chevron-right',
];

function loadDefaultAttributes() {
  const src = fs.readFileSync(DEFAULT_ATTRS_FILE, 'utf8');
  const code = src
    .replace(/import [^;]+;\s*/g, '')
    .replace(/export \{ defaultAttributes as default \};?\s*/g, 'module.exports = defaultAttributes;')
    .replace(/# sourceMappingURL=.*/g, '');
  const module = { exports: {} };
  new Function('module', 'exports', 'require', code)(module, module.exports, require);
  return module.exports;
}

function loadTree(modulePath, defaults) {
  const src = fs.readFileSync(modulePath, 'utf8');
  const code = src
    .replace(/import defaultAttributes from '\.\.\/defaultAttributes\.js';?\s*/g, '')
    .replace(/export \{ (\w+) as default \};?\s*/g, (m, n) => `module.exports = ${n};`)
    .replace(/# sourceMappingURL=.*/g, '');
  const module = { exports: {} };
  const boot = `const defaultAttributes = ${JSON.stringify(defaults)};\n`;
  new Function('module', 'exports', 'require', boot + code)(module, module.exports, require);
  return module.exports;
}

function attrString(obj) {
  return Object.entries(obj || {})
    .filter(([, v]) => v !== null && v !== undefined && v !== false && v !== '')
    .map(([k, v]) => ` ${k}="${String(v).replace(/"/g, '&quot;')}"`)
    .join('');
}

function render(node) {
  if (Array.isArray(node)) {
    if (node.length === 0) return '';
    if (typeof node[0] === 'string') {
      const tag = node[0];
      if (tag === 'svg') {
        const attrs = node[1] && typeof node[1] === 'object' && !Array.isArray(node[1]) ? node[1] : {};
        const children = node
          .slice(2)
          .map(render)
          .join('');
        return `<svg${attrString(attrs)}${children ? `>${children}</svg>` : ' />'}`;
      }
      const childNodes = [];
      let attrs = {};
      for (const part of node.slice(1)) {
        if (Array.isArray(part)) childNodes.push(part);
        else if (part && typeof part === 'object') attrs = Object.assign(attrs, part);
        else if (typeof part === 'string') childNodes.push(part);
      }
      const inner = childNodes.map(render).join('');
      return `<${tag}${attrString(attrs)}${inner ? `>${inner}</${tag}>` : ' />'}`;
    }
    return node.map(render).join('');
  }
  return typeof node === 'string' ? node : '';
}

function main() {
  const defaults = loadDefaultAttributes();
  const icons = {};
  for (const name of NEEDED_ICONS) {
    const file = path.join(ICONS_DIR, `${name}.js`);
    if (!fs.existsSync(file)) throw new Error(`Missing lucide icon: ${name}`);
    const tree = loadTree(file);
    if (defaults) tree[1] = Object.assign(tree[1] || {}, defaults);
    icons[name] = render(tree);
  }

  const banner = '// Generated by scripts/generate-icons.js — do not edit.\n';
  const body = `${banner}window.LUCIDE_ICONS = ${JSON.stringify(icons, null, 2)};`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log(`Wrote ${OUT} (${Object.keys(icons).length} icons)`);
}

main();